language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install boto pytest

script:
  - python -m pytest sputnik/ --remote
